### ISSUE TITLE
no mechanism to exclude word for replacement - missed feature

### ISSUE THREAD

**Issue by enotanet** [SPQRInc/pagekit-glossary#2]

**Comment by ahoiroman** [comment]
Please specify more exact what you mean.

**Comment by enotanet** [comment]
I meant that I have pages with words I don't want to replace and there would be great feature to exclude in some cases replacement. May be some sort of syntax user may use to keep original word without popup.

**Comment by enotanet** [comment]
pagekit and all plugins just amazing work done...

**Comment by ahoiroman** [comment]
I will consider this. At the moment all linked items are excluded automatically.

**Comment by ahoiroman** [comment]
Possible since version 1.0.7
